### ISSUE TITLE
Flutter Web Auth 2.1.3 does not use the correct Flutter Web Auth 2 Platform Interfaces

### ISSUE THREAD

**Issue by Knupper** [ThexXTURBOXx/flutter_web_auth_2#41]
## To Reproduce
1. Update the version to ^2.1.3
2. try to run tests
3. try to run the code

## Expected behavior
The minor version update should work without any problems

## Actual behavior

it does not work for chrome or tests are not running

```
: Error: The method 'FlutterWebAuth2WindowsPlugin.authenticate' doesn't have the named parameter 'contextArgs' of overridden method 'FlutterWebAuth2Platform.authenticate'.
flutter_web_auth_2_windows.dart:55
  Future<String> authenticate({
                 ^
: Context: This is the overridden method ('authenticate').
flutter_web_auth_2_platform_interface.dart:26

```

## Device (please complete the following information!)
 - Browser: Chrome
 - `flutter_web_auth_2` version: update ^2.1.2 to 2.1.3

## Additional context
the newest version still points on the flutter web auth 2 platform version 2.1.0 instead of 2.1.3. As this is a breaking change we should use semantic versioning instead of increasing a minor version. so it should be 2.2.0

## Checklist
 - [x] I have read and followed the **entire** [troubleshooting guide](https://github.com/ThexXTURBOXx/flutter_web_auth_2#troubleshooting) and it has not provided the solution I need.
 - [x] I have provided all the information I can (incl. auth URL etc.)

**Comment by ThexXTURBOXx** [comment]
This issue seems to be semi-valid.
`flutter_web_auth_2` is using proper [Caret Syntax](https://dart.dev/tools/pub/dependencies#caret-syntax) which should enable you to properly upgrade the dependencies using `flutter pub upgrade`.
If you are only using `flutter pub get`, this won't work.
Because of this, the only thing that is wrong right now is the constraint `flutter_web_auth_2_platform_interface: ^2.1.0` (which, again, should not matter if you are doing a proper upgrade).
The next version will properly increase the needed version.
Also, your PR only increases the minor version (see [SemVer](https://semver.org/)) which would also just indicate that the functionality is compatible with the current API (which it kind of is if you properly update). Hence, only the patch update :)

**Comment by ThexXTURBOXx** [comment]
I have increased the version even though it should be unnecessary. I hope this is fixed now :)
