### ISSUE TITLE
Android build not compiling flutter_web_auth_2 anymore

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [ThexXTURBOXx/flutter_web_auth_2#80]
## Describe the bug
I'm trying to compile my flutter app for android but I'm getting the following error:

```
Execution failed for task ':flutter_web_auth_2:compileReleaseJavaWithJavac'.
> error: invalid source release: 16
```

I actually tried everyting from increasing version etc. but I'm always getting the same error.

## Device (please complete the following information!)
 - OS: Android
 - `flutter_web_auth_2` version: 2.2.1

## Checklist
 - [x] I have read and followed the **entire** [troubleshooting guide](https://github.com/ThexXTURBOXx/flutter_web_auth_2#troubleshooting) and it has not provided the solution I need.
 - [y] I have provided all the information I can (incl. auth URL etc.)

**Comment by mariomurrent-softwaresolutions** [comment]
Yeah, the problem is that appwrite has a version constraint on everything < 3 :( ... So I cannot upgrade the package ...
Any other idea? It is working perfectly on iOS :(

**Comment by ThexXTURBOXx** [comment]
Ah, so you are using this package through appwrite!
Sadly, I am unsure what the problem seems to be, but I can imagine it is because of https://github.com/ThexXTURBOXx/flutter_web_auth_2/commit/96a58a6c930a8e8132101325c6a5214b7b1dd829.
However, that has been fixed in versions `3.x` of `flutter_web_auth_2`.
I have already opened https://github.com/appwrite/sdk-generator/pull/723, but it has not been accepted yet.
Another possibility would be to specify `flutter_web_auth_2: 2.1.5` which does not have this constraint.
Otherwise, you sadly have to wait until https://github.com/appwrite/sdk-generator/pull/723 is merged and published

**Comment by mariomurrent-softwaresolutions** [comment]
Oh damn, I was searching half a day and did not find anything ...
Thanks for the hint ...

I just added 2.1.5 to the pubspec.yaml ... this should be enough?

**Comment by mariomurrent-softwaresolutions** [comment]
Well I tried version 2.1.4 which actually was not working. but 2.1.5 did the trick - thank you very much

**Comment by mariomurrent-softwaresolutions** [comment]
Well I tried version 2.1.4 which actually was not working. but 2.1.5 did the trick - thank you very much

**Comment by ThexXTURBOXx** [comment]
It's weird that 2.1.4 did not work, but very nice to hear that at least 2.1.5 worked for you!
I will close this issue and hope that my PR will get merged on appwrite's side rather sooner than later!

**Comment by mariomurrent-softwaresolutions** [comment]
Yeah. 
That’s okay, thanks for the fast reply and help 😊
